services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filters_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: